apiVersion: v1 
kind: Service 
metadata:
  name: mysqlsvc
spec:
  selector:
    app: mysql
  ports: 
  - port: 3306
    targetPort: 3306
    protocol: TCP
  clusterIP: None                     #NO IP ADDRESS 


# FQDN - Fully Qualified Domain Name
# headlesssvcname.namespacename.svc.cluster.local.    service fqdn
# statefulsetname.headlesssvcname.namespacename.svc.cluster.local.    sts fqdn
# mysql.mysqlsvc.default.svc.cluster.local
# mysql-0.mysql.mysqlsvc.default.svc.cluster.local    pod fqdn