apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-file-vol 
spec:
  capacity:
    storage: 1Ti
  nfs:
    path: /vol01
    server: 10.65.207.218
  accessModes: 
    - ReadWriteMany
  claimRef:
    namespace: default
    name: manual-file-vol-claim 
  persistentVolumeReclaimPolicy: Retain