apiVersion: apps/v1
kind: Deployment  #Controller - Self Healing
metadata: 
  name: httpd-deployment
  labels:
    app: httpd 
spec: 
  replicas: 10     #Replicaset
  selector:
    matchLabels:
      app: httpd
  template:
    metadata: 
      name: httpd-pod
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd-main 
          image: httpd:latest
          ports:
            - containerPort: 80